name: fuzzy_chat
description: End to End encripted chat, It's content is stored llocally only and can be read only by chat members
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  file_picker: ^8.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dropzone: ^4.0.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  get_it: ^8.0.0
  go_router: ^13.0.1
  intl: ^0.19.0
  isar:
    hosted: https://pub.isar-community.dev
    version: ^3.1.8
  isar_flutter_libs:
    hosted: https://pub.isar-community.dev
    version: ^3.1.8
  logger: ^2.4.0
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  pointycastle: ^3.7.4
  shared_preferences: ^2.3.2
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter

  isar_generator:
    hosted: https://pub.isar-community.dev
    version: ^3.1.8
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
